<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2017.0.2.363
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Отправка ESTET, Новый клиент!',
	'heading' => 'Отправка новой формы',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Отмечено',
		'checkbox_unchecked' => 'Флажок не установлен',
		'submitted_from' => 'Формы, отправленные с веб-сайта: %s',
		'submitted_by' => 'IP-адрес посетителя: %s',
		'too_many_submissions' => 'Недопустимо высокое количество отправок с этого IP-адреса за последнее время',
		'failed_to_send_email' => 'Не удалось отправить сообщение эл. почты',
		'invalid_reCAPTCHA_private_key' => 'Недействительный закрытый ключ reCAPTCHA.',
		'invalid_reCAPTCHA2_private_key' => 'Недействительный закрытый ключ reCAPTCHA 2.0.',
		'invalid_reCAPTCHA2_server_response' => 'Недействительный ответ сервера reCAPTCHA 2.0.',
		'invalid_field_type' => 'Неизвестный тип поля \'%s\'.',
		'invalid_form_config' => 'Недопустимая конфигурация поля \"%s\".',
		'unknown_method' => 'Неизвестный метод запроса сервера'
	),
	'email' => array(
		'from' => 'mulino43@yandex.ru',
		'to' => 'mulino43@yandex.ru'
	),
	'recaptcha2' => array(
		'private_key' => '6LcqXjkUAAAAAHP9vvvvHCic7jtnMAs6afohasIo'
	),
	'fields' => array(
		'custom_U889' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Name',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Name\' не может быть пустым.'
			)
		),
		'Email' => array(
			'order' => 3,
			'type' => 'email',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Email\' не может быть пустым.',
				'format' => 'Поле \'Email\' содержит недействительное сообщение эл. почты.'
			)
		),
		'custom_U901' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Message',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Message\' не может быть пустым.'
			)
		),
		'custom_U6044' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Cell Phone',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Cell Phone\' не может быть пустым.'
			)
		),
		'g-recaptcha-response' => array(
			'order' => 5,
			'type' => 'recaptcha2',
			'label' => 'Image Verification',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Image Verification\' не может быть пустым.',
				'format' => 'Недействительное значение reCAPTCHA 2.0.'
			)
		),
		'custom_U13810' => array(
			'order' => 6,
			'type' => 'checkbox',
			'label' => ' Нажимая на кнопку «Отправить», вы даете согласие на обработку своих персональных данных',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \' Нажимая на кнопку «Отправить», вы даете согласие на обработку своих персональных данных\' не может быть пустым.'
			)
		)
	)
);

process_form($form);
?>
